#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;


$root = $action [$program] [$courtesy];


$action =   (włącz | odpal | puść | otwórz | uruchom){run}|
            wyżej {up} |
            niżej {down} |
            góra {home} |
            (zaznacz | zaznacz wszystko) {select_all} |
            (kopiuj | skopiuj) {copy} |
            wklej {paste} |
            zapisz {save} |
            cofnij {undo} |
            (zgoogluj | sprawdź w google) {google} |
            zamknij {close} |
            (pokaż pulpit | wróć na pulpit | pulpit) {desktop}
            (dyktuj | rozpocznij dyktowanie) {dictate} |
            czy joda był żydem {yoda} |
            przegądanie prywatne {private_browsing};


$program =  (opera | operę) {opera} |
            (chrome | chroma) {chrome} |
            edge {edge} |
            (notatnik | dokument tekstowy) {notepad};
            przegądanie prywatne {private_browsing};


$courtesy = proszę;
